/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class Buku extends javax.swing.JFrame {

    
    public Buku() {
        initComponents();
    }
    
    public Statement st;
    public ResultSet rs;
    Connection koneksi = ConnectDB.BukaKoneksi();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pengarang = new javax.swing.JPanel();
        lbljudul = new javax.swing.JLabel();
        txtjudul = new javax.swing.JTextField();
        lblpengarang = new javax.swing.JLabel();
        lblpenerbit = new javax.swing.JLabel();
        lblissbn = new javax.swing.JLabel();
        lbljumlah_salinan = new javax.swing.JLabel();
        lblringkasan = new javax.swing.JLabel();
        txtpenerbit = new javax.swing.JTextField();
        txtringkasan = new javax.swing.JTextField();
        txtjumlah_salinan = new javax.swing.JTextField();
        txtissbn = new javax.swing.JTextField();
        txtpengarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelbuku = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnload = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 40, 98), 4));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 40, 98), 4));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("FORM ENTRY BOOK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pengarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 40, 98), 4));

        lbljudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbljudul.setText("Judul Buku ");

        txtjudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtjudul.setToolTipText("");
        txtjudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjudulActionPerformed(evt);
            }
        });

        lblpengarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblpengarang.setText("Pengarang");

        lblpenerbit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblpenerbit.setText("Penerbit");

        lblissbn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblissbn.setText("Issbn");

        lbljumlah_salinan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbljumlah_salinan.setText("Jumlah Salinan");

        lblringkasan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblringkasan.setText("Ringkasan");

        txtpenerbit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpenerbit.setToolTipText("");
        txtpenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpenerbitActionPerformed(evt);
            }
        });

        txtringkasan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtringkasan.setToolTipText("");
        txtringkasan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtringkasanActionPerformed(evt);
            }
        });

        txtjumlah_salinan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtjumlah_salinan.setToolTipText("");
        txtjumlah_salinan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah_salinanActionPerformed(evt);
            }
        });

        txtissbn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtissbn.setToolTipText("");
        txtissbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtissbnActionPerformed(evt);
            }
        });

        txtpengarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpengarang.setToolTipText("");
        txtpengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpengarangActionPerformed(evt);
            }
        });

        tabelbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Judul", "Pengarang", "Penerbit", "Issbn", "Jumlah Salinan", "Ringkasan"
            }
        ));
        jScrollPane1.setViewportView(tabelbuku);

        btnadd.setBackground(new java.awt.Color(51, 255, 0));
        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(255, 255, 0));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(255, 0, 0));
        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnload.setBackground(new java.awt.Color(0, 0, 255));
        btnload.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnload.setText("Load");
        btnload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloadActionPerformed(evt);
            }
        });

        btnexit.setBackground(new java.awt.Color(255, 51, 0));
        btnexit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btnrefresh.setBackground(new java.awt.Color(0, 0, 255));
        btnrefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnload, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnload, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pengarangLayout = new javax.swing.GroupLayout(pengarang);
        pengarang.setLayout(pengarangLayout);
        pengarangLayout.setHorizontalGroup(
            pengarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengarangLayout.createSequentialGroup()
                .addGroup(pengarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pengarangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pengarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pengarangLayout.createSequentialGroup()
                                .addComponent(lbljudul, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtjudul))
                            .addGroup(pengarangLayout.createSequentialGroup()
                                .addComponent(lblpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtpenerbit))
                            .addGroup(pengarangLayout.createSequentialGroup()
                                .addGroup(pengarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbljumlah_salinan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(lblpengarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblissbn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblringkasan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pengarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtringkasan, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtjumlah_salinan)
                                    .addComponent(txtissbn)
                                    .addComponent(txtpengarang)))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        pengarangLayout.setVerticalGroup(
            pengarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengarangLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(pengarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtjudul, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lbljudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpengarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(lblpenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtissbn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblissbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbljumlah_salinan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtjumlah_salinan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblringkasan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pengarangLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtringkasan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pengarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pengarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtjudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjudulActionPerformed

    private void txtpenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenerbitActionPerformed

    private void txtringkasanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtringkasanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtringkasanActionPerformed

    private void txtjumlah_salinanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah_salinanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah_salinanActionPerformed

    private void txtissbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtissbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtissbnActionPerformed

    private void txtpengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpengarangActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
                                           
        String judul = txtjudul.getText();
        String pengarang = txtpengarang.getText();
        String penerbit = txtpenerbit.getText();
        String issbn = txtissbn.getText();
        String jumlah_salinan = txtjumlah_salinan.getText();
        String ringkasan = txtringkasan.getText();

        if (judul.isEmpty() || pengarang.isEmpty() || penerbit.isEmpty() || issbn.isEmpty() || jumlah_salinan.isEmpty() || ringkasan.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua field harus diisi", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sql = "INSERT INTO buku (judul, pengarang, penerbit, issbn, jumlah_salinan, ringkasan) VALUES (?, ?, ?, ?, ?, ?)";
        String loadData = "SELECT * FROM buku";
        
        try {
            PreparedStatement stmt = koneksi.prepareStatement(sql);
            stmt.setString(1, judul);
            stmt.setString(2, pengarang);
            stmt.setString(3, penerbit);
            stmt.setString(4, issbn);
            stmt.setString(5, jumlah_salinan);
            stmt.setString(6, ringkasan);
            
            int rowsInserted = stmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(null, "Data buku berhasil ditambahkan!");
                Statement stmtn = koneksi.createStatement();
                ResultSet rs = stmtn.executeQuery(loadData);

                DefaultTableModel model = new DefaultTableModel();
                tabelbuku.setModel(model);

                model.addColumn("ID");
                model.addColumn("Judul");
                model.addColumn("Pengarang");
                model.addColumn("Penerbit");
                model.addColumn("ISSBN");
                model.addColumn("Jumlah Salinan");
                model.addColumn("Ringkasan");

                model.setRowCount(0);

                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("id_buku"),
                        rs.getString("judul"),
                        rs.getString("pengarang"),
                        rs.getString("penerbit"),
                        rs.getString("issbn"),
                        rs.getInt("jumlah_salinan"),
                        rs.getString("ringkasan")
                    });
                }
                txtjudul.setText("");
                txtpengarang.setText("");
                txtpenerbit.setText("");
                txtissbn.setText("");
                txtjumlah_salinan.setText("");
                txtringkasan.setText("");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
   
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        int selectedRow = tabelbuku.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih buku yang ingin diupdate", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int idBuku = (int) tabelbuku.getValueAt(selectedRow, 0);
        String judul = txtjudul.getText();
        String pengarang = txtpengarang.getText();
        String penerbit = txtpenerbit.getText();
        String issbn = txtissbn.getText();
        int jumlahSalinan = Integer.parseInt(txtjumlah_salinan.getText());
        String ringkasan = txtringkasan.getText();
        
        String sql = "UPDATE buku SET judul = ?, pengarang = ?, penerbit = ?, issbn = ?, jumlah_salinan = ?, ringkasan = ? WHERE id_buku = ?";
        String loadData = "SELECT * FROM buku";
        
        try {
            PreparedStatement pstmt = koneksi.prepareStatement(sql);
            pstmt.setString(1, judul);
            pstmt.setString(2, pengarang);
            pstmt.setString(3, penerbit);
            pstmt.setString(4, issbn);
            pstmt.setInt(5, jumlahSalinan);
            pstmt.setString(6, ringkasan);
            pstmt.setInt(7, idBuku);
            
            int rowsUpdated = pstmt.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Data buku berhasil diupdate!");
                Statement stmt = koneksi.createStatement();
                ResultSet rs = stmt.executeQuery(loadData);

                DefaultTableModel model = new DefaultTableModel();
                tabelbuku.setModel(model);

                model.addColumn("ID");
                model.addColumn("Judul");
                model.addColumn("Pengarang");
                model.addColumn("Penerbit");
                model.addColumn("ISSBN");
                model.addColumn("Jumlah Salinan");
                model.addColumn("Ringkasan");

                model.setRowCount(0);

                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("id_buku"),
                        rs.getString("judul"),
                        rs.getString("pengarang"),
                        rs.getString("penerbit"),
                        rs.getString("issbn"),
                        rs.getInt("jumlah_salinan"),
                        rs.getString("ringkasan")
                    });
                }
                
                txtjudul.setText("");
                txtpengarang.setText("");
                txtpenerbit.setText("");
                txtissbn.setText("");
                txtjumlah_salinan.setText("");
                txtringkasan.setText("");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int selectedRow = tabelbuku.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih buku yang ingin dihapus", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int idBuku = (int) tabelbuku.getValueAt(selectedRow, 0);
        
        String sql = "DELETE FROM buku WHERE id_buku = ?";
        String loadData = "SELECT * FROM buku";
        
        try {
            PreparedStatement pstmt = koneksi.prepareStatement(sql);
            pstmt.setInt(1, idBuku);
            
            int rowsDeleted = pstmt.executeUpdate();
            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(null, "Data buku berhasil dihapus!");
                Statement stmt = koneksi.createStatement();
                ResultSet rs = stmt.executeQuery(loadData);

                DefaultTableModel model = new DefaultTableModel();
                tabelbuku.setModel(model);

                model.addColumn("ID");
                model.addColumn("Judul");
                model.addColumn("Pengarang");
                model.addColumn("Penerbit");
                model.addColumn("ISSBN");
                model.addColumn("Jumlah Salinan");
                model.addColumn("Ringkasan");

                model.setRowCount(0);

                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("id_buku"),
                        rs.getString("judul"),
                        rs.getString("pengarang"),
                        rs.getString("penerbit"),
                        rs.getString("issbn"),
                        rs.getInt("jumlah_salinan"),
                        rs.getString("ringkasan")
                    });
                }
                txtjudul.setText("");
                txtpengarang.setText("");
                txtpenerbit.setText("");
                txtissbn.setText("");
                txtjumlah_salinan.setText("");
                txtringkasan.setText("");
                
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloadActionPerformed
        String sql = "SELECT * FROM buku";
        
        try {
            Statement stmt = koneksi.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            DefaultTableModel model = new DefaultTableModel();
            tabelbuku.setModel(model);

            model.addColumn("ID");
            model.addColumn("Judul");
            model.addColumn("Pengarang");
            model.addColumn("Penerbit");
            model.addColumn("ISSBN");
            model.addColumn("Jumlah Salinan");
            model.addColumn("Ringkasan");
            
            model.setRowCount(0);
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_buku"),
                    rs.getString("judul"),
                    rs.getString("pengarang"),
                    rs.getString("penerbit"),
                    rs.getString("issbn"),
                    rs.getInt("jumlah_salinan"),
                    rs.getString("ringkasan")
                });
            }
            
            tabelbuku.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent event) {
                    if (!event.getValueIsAdjusting()) {
                        int selectedRow = tabelbuku.getSelectedRow();
                        if (selectedRow != -1) {
                            int idBuku = (int) model.getValueAt(selectedRow, 0);

                            String query = "SELECT * FROM buku WHERE id_buku = ?";
                            try {
                                PreparedStatement pstmt = koneksi.prepareStatement(query);
                                pstmt.setInt(1, idBuku);
                                ResultSet rs = pstmt.executeQuery();

                                if (rs.next()) {
                                    txtjudul.setText(rs.getString("judul"));
                                    txtpengarang.setText(rs.getString("pengarang"));
                                    txtpenerbit.setText(rs.getString("penerbit"));
                                    txtissbn.setText(rs.getString("issbn"));
                                    txtjumlah_salinan.setText(rs.getString("jumlah_salinan"));
                                    txtringkasan.setText(rs.getString("ringkasan"));
                                }
                            } catch (SQLException ex) {
                                ex.printStackTrace();
                                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
                            }
                        }
                    }
                }
            });

            
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
     
    }//GEN-LAST:event_btnloadActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        txtjudul.setText("");
        txtpengarang.setText("");
        txtpenerbit.setText("");
        txtissbn.setText("");
        txtjumlah_salinan.setText("");
        txtringkasan.setText("");
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnload;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblissbn;
    private javax.swing.JLabel lbljudul;
    private javax.swing.JLabel lbljumlah_salinan;
    private javax.swing.JLabel lblpenerbit;
    private javax.swing.JLabel lblpengarang;
    private javax.swing.JLabel lblringkasan;
    private javax.swing.JPanel pengarang;
    private javax.swing.JTable tabelbuku;
    private javax.swing.JTextField txtissbn;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtjumlah_salinan;
    private javax.swing.JTextField txtpenerbit;
    private javax.swing.JTextField txtpengarang;
    private javax.swing.JTextField txtringkasan;
    // End of variables declaration//GEN-END:variables
}
